dependencies:
  - python=3.8
  - pip=21.1.1
  - pip:
    # Protobuf is needed tp avoid conflict with managed spark
    - protobuf==3.19.6
    # Feature store core SDK
    - https://featurestoreprp.blob.core.windows.net/test-sdk/azureml_featurestore-0.0.1-py3-none-any.whl
    # Azure ML CRUD SDK
    - https://featurestoreprp.blob.core.windows.net/test-sdk/azure_ai_ml-1.7.0-py3-none-any.whl    
    # This is needed if you want to execute "SDK+CLI" track in the docs tutorial
    - azure-cli    
    # NOTE: This is only needed for setting up materialization which includes offline store creation, UAI creation and setting up RBAC. This is part of Part 2 of the tutorial.
    - azure-mgmt-storage
    - azure-mgmt-msi
    - azure-mgmt-authorization
    - azure-storage-file-datalake

    # Following are required for training and batch inference pipeline of *this* sample. Users can remove this for their own projects
    - scikit-learn
    - pandas
name: fs_env
